### ISSUE TITLE
Error while deploying with heroku

### ISSUE THREAD

**Issue by RodolfoSilva** [hasura/graphql-engine-heroku#52]
```
=== Fetching app code
=== Building web (Dockerfile)
Sending build context to Docker daemon  585.2kBStep 1/3 : FROM hasura/graphql-engine:v1.0.0-beta.01
manifest for hasura/graphql-engine:v1.0.0-beta.01 not found
```

![image](https://user-images.githubusercontent.com/1703020/57849652-36df5200-77b2-11e9-8dfc-b6802a0241b4.png)

**Comment by RodolfoSilva** [comment]
@shahidhk @coco98 @arvi3411301

**Comment by shahidhk** [comment]
@RodolfoSilva we had some issues with last release, pushing an update in a while. Heroku repo has been reverted to deploy alpha45, thanks for letting us know.

**Comment by RodolfoSilva** [comment]
:D
