### ISSUE TITLE
Can Hasura be autoscaled on Heroku?

### ISSUE THREAD

**Issue by DominikGuzei** [hasura/graphql-engine-heroku#62]
Hey 👋 first i want to say thanks for this amazing project 🥇 

Im currently starting a new project and would like to keep the necessary devops to a minimum, so i thought to setup Hasura on Heroku … thinking about the future it would be a dream if i could just scale the heroku dynos to multiple instances - but would that work? And if not automatically, what would be necessary to achieve that (if possible)?

**Comment by joserocha3** [comment]
I am hosting Hasura on Heroku. I am using standard dynos, so I do not get the autoscale option. However, I am able to manually add/remove dynos as needed.

[This issue](https://github.com/hasura/graphql-engine/issues/2083) mentions autoscaling with Heroku as well.
